// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/favonia/cloudflare-ddns/internal/provider (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -typed -destination=../mocks/mock_provider.go -package=mocks . Provider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ipnet "github.com/favonia/cloudflare-ddns/internal/ipnet"
	pp "github.com/favonia/cloudflare-ddns/internal/pp"
	provider "github.com/favonia/cloudflare-ddns/internal/provider"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetRawData mocks base method.
func (m *MockProvider) GetRawData(ctx context.Context, ppfmt pp.PP, ipFamily ipnet.Family, defaultPrefixLen int) provider.DetectionResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRawData", ctx, ppfmt, ipFamily, defaultPrefixLen)
	ret0, _ := ret[0].(provider.DetectionResult)
	return ret0
}

// GetRawData indicates an expected call of GetRawData.
func (mr *MockProviderMockRecorder) GetRawData(ctx, ppfmt, ipFamily, defaultPrefixLen any) *MockProviderGetRawDataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRawData", reflect.TypeOf((*MockProvider)(nil).GetRawData), ctx, ppfmt, ipFamily, defaultPrefixLen)
	return &MockProviderGetRawDataCall{Call: call}
}

// MockProviderGetRawDataCall wrap *gomock.Call
type MockProviderGetRawDataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderGetRawDataCall) Return(arg0 provider.DetectionResult) *MockProviderGetRawDataCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderGetRawDataCall) Do(f func(context.Context, pp.PP, ipnet.Family, int) provider.DetectionResult) *MockProviderGetRawDataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderGetRawDataCall) DoAndReturn(f func(context.Context, pp.PP, ipnet.Family, int) provider.DetectionResult) *MockProviderGetRawDataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsExplicitEmpty mocks base method.
func (m *MockProvider) IsExplicitEmpty() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExplicitEmpty")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsExplicitEmpty indicates an expected call of IsExplicitEmpty.
func (mr *MockProviderMockRecorder) IsExplicitEmpty() *MockProviderIsExplicitEmptyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExplicitEmpty", reflect.TypeOf((*MockProvider)(nil).IsExplicitEmpty))
	return &MockProviderIsExplicitEmptyCall{Call: call}
}

// MockProviderIsExplicitEmptyCall wrap *gomock.Call
type MockProviderIsExplicitEmptyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderIsExplicitEmptyCall) Return(arg0 bool) *MockProviderIsExplicitEmptyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderIsExplicitEmptyCall) Do(f func() bool) *MockProviderIsExplicitEmptyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderIsExplicitEmptyCall) DoAndReturn(f func() bool) *MockProviderIsExplicitEmptyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *MockProviderNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
	return &MockProviderNameCall{Call: call}
}

// MockProviderNameCall wrap *gomock.Call
type MockProviderNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderNameCall) Return(arg0 string) *MockProviderNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderNameCall) Do(f func() string) *MockProviderNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderNameCall) DoAndReturn(f func() string) *MockProviderNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
