// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/favonia/cloudflare-ddns/internal/heartbeat (interfaces: BasicHeartbeat,Heartbeat)
//
// Generated by this command:
//
//	mockgen -typed -destination=../mocks/mock_heartbeat.go -package=mocks . BasicHeartbeat,Heartbeat
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	heartbeat "github.com/favonia/cloudflare-ddns/internal/heartbeat"
	pp "github.com/favonia/cloudflare-ddns/internal/pp"
	gomock "go.uber.org/mock/gomock"
)

// MockBasicHeartbeat is a mock of BasicHeartbeat interface.
type MockBasicHeartbeat struct {
	ctrl     *gomock.Controller
	recorder *MockBasicHeartbeatMockRecorder
	isgomock struct{}
}

// MockBasicHeartbeatMockRecorder is the mock recorder for MockBasicHeartbeat.
type MockBasicHeartbeatMockRecorder struct {
	mock *MockBasicHeartbeat
}

// NewMockBasicHeartbeat creates a new mock instance.
func NewMockBasicHeartbeat(ctrl *gomock.Controller) *MockBasicHeartbeat {
	mock := &MockBasicHeartbeat{ctrl: ctrl}
	mock.recorder = &MockBasicHeartbeatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasicHeartbeat) EXPECT() *MockBasicHeartbeatMockRecorder {
	return m.recorder
}

// Describe mocks base method.
func (m *MockBasicHeartbeat) Describe(yield func(string, string) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Describe", yield)
}

// Describe indicates an expected call of Describe.
func (mr *MockBasicHeartbeatMockRecorder) Describe(yield any) *MockBasicHeartbeatDescribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Describe", reflect.TypeOf((*MockBasicHeartbeat)(nil).Describe), yield)
	return &MockBasicHeartbeatDescribeCall{Call: call}
}

// MockBasicHeartbeatDescribeCall wrap *gomock.Call
type MockBasicHeartbeatDescribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBasicHeartbeatDescribeCall) Return() *MockBasicHeartbeatDescribeCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBasicHeartbeatDescribeCall) Do(f func(func(string, string) bool)) *MockBasicHeartbeatDescribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBasicHeartbeatDescribeCall) DoAndReturn(f func(func(string, string) bool)) *MockBasicHeartbeatDescribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockBasicHeartbeat) Ping(ctx context.Context, ppfmt pp.PP, msg heartbeat.Message) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx, ppfmt, msg)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockBasicHeartbeatMockRecorder) Ping(ctx, ppfmt, msg any) *MockBasicHeartbeatPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockBasicHeartbeat)(nil).Ping), ctx, ppfmt, msg)
	return &MockBasicHeartbeatPingCall{Call: call}
}

// MockBasicHeartbeatPingCall wrap *gomock.Call
type MockBasicHeartbeatPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBasicHeartbeatPingCall) Return(arg0 bool) *MockBasicHeartbeatPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBasicHeartbeatPingCall) Do(f func(context.Context, pp.PP, heartbeat.Message) bool) *MockBasicHeartbeatPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBasicHeartbeatPingCall) DoAndReturn(f func(context.Context, pp.PP, heartbeat.Message) bool) *MockBasicHeartbeatPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockHeartbeat is a mock of Heartbeat interface.
type MockHeartbeat struct {
	ctrl     *gomock.Controller
	recorder *MockHeartbeatMockRecorder
	isgomock struct{}
}

// MockHeartbeatMockRecorder is the mock recorder for MockHeartbeat.
type MockHeartbeatMockRecorder struct {
	mock *MockHeartbeat
}

// NewMockHeartbeat creates a new mock instance.
func NewMockHeartbeat(ctrl *gomock.Controller) *MockHeartbeat {
	mock := &MockHeartbeat{ctrl: ctrl}
	mock.recorder = &MockHeartbeatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeartbeat) EXPECT() *MockHeartbeatMockRecorder {
	return m.recorder
}

// Describe mocks base method.
func (m *MockHeartbeat) Describe(yield func(string, string) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Describe", yield)
}

// Describe indicates an expected call of Describe.
func (mr *MockHeartbeatMockRecorder) Describe(yield any) *MockHeartbeatDescribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Describe", reflect.TypeOf((*MockHeartbeat)(nil).Describe), yield)
	return &MockHeartbeatDescribeCall{Call: call}
}

// MockHeartbeatDescribeCall wrap *gomock.Call
type MockHeartbeatDescribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHeartbeatDescribeCall) Return() *MockHeartbeatDescribeCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHeartbeatDescribeCall) Do(f func(func(string, string) bool)) *MockHeartbeatDescribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHeartbeatDescribeCall) DoAndReturn(f func(func(string, string) bool)) *MockHeartbeatDescribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Exit mocks base method.
func (m *MockHeartbeat) Exit(ctx context.Context, ppfmt pp.PP, message string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exit", ctx, ppfmt, message)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exit indicates an expected call of Exit.
func (mr *MockHeartbeatMockRecorder) Exit(ctx, ppfmt, message any) *MockHeartbeatExitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exit", reflect.TypeOf((*MockHeartbeat)(nil).Exit), ctx, ppfmt, message)
	return &MockHeartbeatExitCall{Call: call}
}

// MockHeartbeatExitCall wrap *gomock.Call
type MockHeartbeatExitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHeartbeatExitCall) Return(arg0 bool) *MockHeartbeatExitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHeartbeatExitCall) Do(f func(context.Context, pp.PP, string) bool) *MockHeartbeatExitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHeartbeatExitCall) DoAndReturn(f func(context.Context, pp.PP, string) bool) *MockHeartbeatExitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Log mocks base method.
func (m *MockHeartbeat) Log(ctx context.Context, ppfmt pp.PP, msg heartbeat.Message) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", ctx, ppfmt, msg)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockHeartbeatMockRecorder) Log(ctx, ppfmt, msg any) *MockHeartbeatLogCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockHeartbeat)(nil).Log), ctx, ppfmt, msg)
	return &MockHeartbeatLogCall{Call: call}
}

// MockHeartbeatLogCall wrap *gomock.Call
type MockHeartbeatLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHeartbeatLogCall) Return(arg0 bool) *MockHeartbeatLogCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHeartbeatLogCall) Do(f func(context.Context, pp.PP, heartbeat.Message) bool) *MockHeartbeatLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHeartbeatLogCall) DoAndReturn(f func(context.Context, pp.PP, heartbeat.Message) bool) *MockHeartbeatLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockHeartbeat) Ping(ctx context.Context, ppfmt pp.PP, msg heartbeat.Message) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx, ppfmt, msg)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockHeartbeatMockRecorder) Ping(ctx, ppfmt, msg any) *MockHeartbeatPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockHeartbeat)(nil).Ping), ctx, ppfmt, msg)
	return &MockHeartbeatPingCall{Call: call}
}

// MockHeartbeatPingCall wrap *gomock.Call
type MockHeartbeatPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHeartbeatPingCall) Return(arg0 bool) *MockHeartbeatPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHeartbeatPingCall) Do(f func(context.Context, pp.PP, heartbeat.Message) bool) *MockHeartbeatPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHeartbeatPingCall) DoAndReturn(f func(context.Context, pp.PP, heartbeat.Message) bool) *MockHeartbeatPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *MockHeartbeat) Start(ctx context.Context, ppfmt pp.PP, message string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, ppfmt, message)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockHeartbeatMockRecorder) Start(ctx, ppfmt, message any) *MockHeartbeatStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockHeartbeat)(nil).Start), ctx, ppfmt, message)
	return &MockHeartbeatStartCall{Call: call}
}

// MockHeartbeatStartCall wrap *gomock.Call
type MockHeartbeatStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHeartbeatStartCall) Return(arg0 bool) *MockHeartbeatStartCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHeartbeatStartCall) Do(f func(context.Context, pp.PP, string) bool) *MockHeartbeatStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHeartbeatStartCall) DoAndReturn(f func(context.Context, pp.PP, string) bool) *MockHeartbeatStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
