// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/favonia/cloudflare-ddns/internal/provider (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -typed -destination=../mocks/mock_provider.go -package=mocks . Provider
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	netip "net/netip"
	reflect "reflect"

	ipnet "github.com/favonia/cloudflare-ddns/internal/ipnet"
	pp "github.com/favonia/cloudflare-ddns/internal/pp"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetIP mocks base method.
func (m *MockProvider) GetIP(arg0 context.Context, arg1 pp.PP, arg2 ipnet.Type, arg3 bool) (netip.Addr, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIP", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(netip.Addr)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetIP indicates an expected call of GetIP.
func (mr *MockProviderMockRecorder) GetIP(arg0, arg1, arg2, arg3 any) *ProviderGetIPCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIP", reflect.TypeOf((*MockProvider)(nil).GetIP), arg0, arg1, arg2, arg3)
	return &ProviderGetIPCall{Call: call}
}

// ProviderGetIPCall wrap *gomock.Call
type ProviderGetIPCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProviderGetIPCall) Return(arg0 netip.Addr, arg1 bool) *ProviderGetIPCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProviderGetIPCall) Do(f func(context.Context, pp.PP, ipnet.Type, bool) (netip.Addr, bool)) *ProviderGetIPCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProviderGetIPCall) DoAndReturn(f func(context.Context, pp.PP, ipnet.Type, bool) (netip.Addr, bool)) *ProviderGetIPCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *ProviderNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
	return &ProviderNameCall{Call: call}
}

// ProviderNameCall wrap *gomock.Call
type ProviderNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProviderNameCall) Return(arg0 string) *ProviderNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProviderNameCall) Do(f func() string) *ProviderNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProviderNameCall) DoAndReturn(f func() string) *ProviderNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ShouldWeCheck1111 mocks base method.
func (m *MockProvider) ShouldWeCheck1111() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldWeCheck1111")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldWeCheck1111 indicates an expected call of ShouldWeCheck1111.
func (mr *MockProviderMockRecorder) ShouldWeCheck1111() *ProviderShouldWeCheck1111Call {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldWeCheck1111", reflect.TypeOf((*MockProvider)(nil).ShouldWeCheck1111))
	return &ProviderShouldWeCheck1111Call{Call: call}
}

// ProviderShouldWeCheck1111Call wrap *gomock.Call
type ProviderShouldWeCheck1111Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProviderShouldWeCheck1111Call) Return(arg0 bool) *ProviderShouldWeCheck1111Call {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProviderShouldWeCheck1111Call) Do(f func() bool) *ProviderShouldWeCheck1111Call {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProviderShouldWeCheck1111Call) DoAndReturn(f func() bool) *ProviderShouldWeCheck1111Call {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
