// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/favonia/cloudflare-ddns/internal/notifier (interfaces: Notifier)
//
// Generated by this command:
//
//	mockgen -typed -destination=../mocks/mock_notifier.go -package=mocks . Notifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notifier "github.com/favonia/cloudflare-ddns/internal/notifier"
	pp "github.com/favonia/cloudflare-ddns/internal/pp"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// Describe mocks base method.
func (m *MockNotifier) Describe(yield func(string, string) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Describe", yield)
}

// Describe indicates an expected call of Describe.
func (mr *MockNotifierMockRecorder) Describe(yield any) *MockNotifierDescribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Describe", reflect.TypeOf((*MockNotifier)(nil).Describe), yield)
	return &MockNotifierDescribeCall{Call: call}
}

// MockNotifierDescribeCall wrap *gomock.Call
type MockNotifierDescribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotifierDescribeCall) Return() *MockNotifierDescribeCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotifierDescribeCall) Do(f func(func(string, string) bool)) *MockNotifierDescribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotifierDescribeCall) DoAndReturn(f func(func(string, string) bool)) *MockNotifierDescribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockNotifier) Send(ctx context.Context, ppfmt pp.PP, msg notifier.Message) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, ppfmt, msg)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotifierMockRecorder) Send(ctx, ppfmt, msg any) *MockNotifierSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotifier)(nil).Send), ctx, ppfmt, msg)
	return &MockNotifierSendCall{Call: call}
}

// MockNotifierSendCall wrap *gomock.Call
type MockNotifierSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotifierSendCall) Return(arg0 bool) *MockNotifierSendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotifierSendCall) Do(f func(context.Context, pp.PP, notifier.Message) bool) *MockNotifierSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotifierSendCall) DoAndReturn(f func(context.Context, pp.PP, notifier.Message) bool) *MockNotifierSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
