version: 2
groups:
  grouped:
    update-types:
      - "minor"
      - "patch"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/.clusterfuzzlite/"
    schedule:
      interval: "daily"
