linters-settings:
  gci:
    local-prefixes: github.com/favonia/cloudflare-ddns
  maligned:
    suggest-new: true
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
        - paralleltest
      text: "does not use range value in test Run"

linters:
  enable-all: true
  disable: maligned,interfacer,nlreturn,wsl
