linters-settings:
  gci:
    sections:
      - standard
      - default
      - pkgPrefix(github.com/favonia/cloudflare-ddns)
  maligned:
    suggest-new: true
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
        - paralleltest
      text: "does not use range value in test Run"

linters:
  enable-all: true
  disable:
    - execinquery # the linter crashes: https://github.com/lufeee/execinquery/issues/3
    - exhaustivestruct # deprecated
    - golint # deprecated
    - interfacer
    - ireturn # ireturn works poorly for the style with private types and public interfaces
    - maligned
    - nlreturn
    - scopelint # deprecated
    - varnamelen # varnamelen complains too much, in my opinion
    - wsl
    - nonamedreturns # named returns are needed in the internal updator package
