linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/favonia/cloudflare-ddns)
  exhaustive:
    default-signifies-exhaustive: true
  govet:
    settings:
      printf:
        funcs:
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).Infof
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).Noticef
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).Warningf
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).Errorf
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).Infof
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).Noticef
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).Warningf
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).Errorf
  revive:
    rules:
      - name: unused-parameter
        arguments:
          - allowRegex: "^_"

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated; replaced by exhaustruct
    - golint # deprecated; replaced by revive
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated, and I value readability over bytes saved by alignment
    - nosnakecase # deprecated; revive's var-naming check seems to be better
    - scopelint # deprecated; replaced by exportloopref
    - structcheck # deprecated
    - varcheck # deprecated

    - cyclop # can detect complicated code, but never leads to actual code changes
    - gocognit # can detect complicated code, but never leads to actual code changes
    - maintidx # can detect complicated code, but never leads to actual code changes

    - depguard # useless; I do not introduce a dependency carelessly
    - gosmopolitan # interesting for i18n checking, useless for this project

    - nlreturn # I don't agree with the style enforced by nlreturn
    - varnamelen # I don't agree with the style enforced by varnamelen
    - wsl # I don't agree with the style enforced by wsl

    - ireturn # doesn't work for private struct types; see https://github.com/butuzov/ireturn/issues/31
    - nonamedreturns # named returns are needed in the internal updater package
