linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/favonia/cloudflare-ddns)
  gosec:
    excludes:
      - G101
  govet:
    settings:
      printf:
        funcs:
          - github.com/favonia/cloudflare-ddns/internal/message.NewMonitorMessagef
          - github.com/favonia/cloudflare-ddns/internal/message.NewNotifierMessagef
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).Infof
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).Noticef
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).InfoOncef
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).NoticeOncef
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).Infof
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).Noticef
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).InfoOncef
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).NoticeOncef
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
      - name: unused-parameter
        arguments:
          - allowRegex: "^_"

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - lll
        - dupl
  include:
    - EXC0002
    - EXC0011
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015

linters:
  enable-all: true
  disable:
    - exportloopref # deprecated

    - goconst # never leads to actual code changes
    - mnd # never leads to actual code changes

    - cyclop # can detect complicated code, but never leads to actual code changes
    - funlen # can detect complicated code, but never leads to actual code changes
    - gocognit # can detect complicated code, but never leads to actual code changes
    - gocyclo # can detect complicated code, but never leads to actual code changes
    - maintidx # can detect complicated code, but never leads to actual code changes
    - nestif # can detect complicated code, but never leads to actual code changes

    - depguard # useless; I do not introduce a dependency carelessly
    - gosmopolitan # interesting for i18n checking, useless for this project

    - nlreturn # I don't agree with the style enforced by nlreturn
    - varnamelen # I don't agree with the style enforced by varnamelen
    - wsl # I don't agree with the style enforced by wsl

    - ireturn # doesn't work for private struct types; see https://github.com/butuzov/ireturn/issues/31
    - nonamedreturns # named returns are needed in the internal setter package for partitioning records
