linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/favonia/cloudflare-ddns)
  maligned:
    suggest-new: true
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
        - paralleltest
      text: "does not use range value in test Run"

linters:
  enable-all: true
  disable:
    - exhaustivestruct # deprecated
    - golint # deprecated
    - interfacer # deprecated
    - ireturn # ireturn works poorly for the style with private types and public interfaces
    - maligned # deprecated, and I value readability over bytes saved by alignment
    - scopelint # deprecated
    - nlreturn # I don't agree with the style enforced by nlreturn
    - varnamelen # varnamelen complains too much, in my opinion
    - wsl # I don't agree with the style enforced by wsl
    - nosnakecase # revive's var-naming check seems to be better
    - nonamedreturns # named returns are needed in the internal updator package
