linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/favonia/cloudflare-ddns)
  exhaustive:
    default-signifies-exhaustive: true
  govet:
    settings:
      printf:
        funcs:
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).Infof
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).Noticef
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).Warningf
          - (github.com/favonia/cloudflare-ddns/internal/pp.PP).Errorf
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).Infof
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).Noticef
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).Warningf
          - (*github.com/favonia/cloudflare-ddns/internal/mocks.MockPPMockRecorder).Errorf
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true

issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
        - paralleltest
      text: "does not use range value in test Run"

linters:
  enable-all: true
  disable:
    - cyclop # The linter can detect complicated code, but it never lead to actual code changes
    - deadcode # deprecated
    - depguard # This is useless. I already carefully documented all non-Google libraries
    - exhaustivestruct # deprecated; replaced by exhaustruct
    - gocognit #  The linter can detect complicated code, but it never lead to actual code changes
    - golint # deprecated; replaced by revive
    - gosmopolitan # The idea is interesting but is useless for this project
    - ifshort # deprecated
    - interfacer # deprecated
    - ireturn # ireturn works poorly for the style with private types and public interfaces
    - maintidx # The linter can detect complicated code, but it never lead to actual code changes
    - maligned # deprecated, and I value readability over bytes saved by alignment
    - nlreturn # I don't agree with the style enforced by nlreturn
    - nonamedreturns # named returns are needed in the internal updater package
    - nosnakecase # revive's var-naming check seems to be better
    - scopelint # deprecated; replaced by exportloopref
    - structcheck # deprecated
    - varcheck # deprecated
    - varnamelen # varnamelen complains too much, in my opinion
    - wsl # I don't agree with the style enforced by wsl
