linters-settings:
  gci:
    local-prefixes: github.com/favonia/cloudflare-ddns-go
  maligned:
    suggest-new: true

linters:
  enable-all: true
  disable: maligned,scopelint,golint,interfacer,nlreturn,wsl,lll
