package main

var allWatches = []config{
	{
		Name:         "Cloudflare IP ranges (IPv4)",
		PageURL:      "https://www.cloudflare.com/ips-v4/",
		ExpectedFile: "../../../internal/ipnet/cloudflare-ips-v4.txt",
		WatchLabel:   "Watched IPv4 ranges",
		Reminders: []string{
			"Re-check the Cloudflare IPv4 ranges used by the trace IP validator.",
			"Update internal/provider/protocol/cloudflare-ips-v4.txt if ranges changed.",
		},
		RelatedPaths: []string{
			"internal/ipnet/cloudflare-ips-v4.txt",
			"internal/ipnet/cloudflare_ranges.go",
			"internal/provider/protocol/cloudflare_trace.go",
		},
	},
	{
		Name:         "Cloudflare IP ranges (IPv6)",
		PageURL:      "https://www.cloudflare.com/ips-v6/",
		ExpectedFile: "../../../internal/ipnet/cloudflare-ips-v6.txt",
		WatchLabel:   "Watched IPv6 ranges",
		Reminders: []string{
			"Re-check the Cloudflare IPv6 ranges used by the trace IP validator.",
			"Update internal/provider/protocol/cloudflare-ips-v6.txt if ranges changed.",
		},
		RelatedPaths: []string{
			"internal/ipnet/cloudflare-ips-v6.txt",
			"internal/ipnet/cloudflare_ranges.go",
			"internal/provider/protocol/cloudflare_trace.go",
		},
	},
	{
		Name:         "Cloudflare dashboard deeplink anchors",
		Repo:         "cloudflare/cloudflare-docs",
		Ref:          "production",
		Path:         "src/content/dash-routes/core.json",
		SnapshotDate: "2026-03-22",
		HistoryURL:   "https://github.com/cloudflare/cloudflare-docs/commits/production/src/content/dash-routes/core.json",
		JSONRouteSelectors: []jsonRouteSelector{
			{
				Label:            "DNS records route",
				Name:             "Records",
				Parent:           []string{"DNS"},
				ExpectedDeeplink: "/?to=/:account/:zone/dns/records",
			},
			{
				Label:            "Account configurations route",
				Name:             "Configurations",
				Parent:           []string{"Manage account"},
				ExpectedDeeplink: "/?to=/:account/configurations",
			},
		},
		WatchLabel: "Watched published dashboard-route anchors",
		Reminders: []string{
			"Re-check cloudflareDNSRecordsDeeplink if the documented DNS records route changes.",
			"Re-check whether the documented account-level Configurations route still exists before trusting the unofficial /lists/:list-id suffix.",
			"Re-check internal/api/cloudflare_dashboard.go and internal/api/cloudflare_dashboard_internal_test.go.",
		},
		RelatedPaths: []string{
			"internal/api/cloudflare_dashboard.go",
			"internal/api/cloudflare_dashboard_internal_test.go",
			"internal/api/cloudflare_records.go",
			"internal/api/cloudflare_waf.go",
		},
	},
	{
		Name:           "Cloudflare DNS record attributes",
		Repo:           "cloudflare/cloudflare-docs",
		Ref:            "production",
		Path:           "src/content/docs/dns/manage-dns-records/reference/record-attributes.mdx",
		SnapshotDate:   "2026-03-22",
		HistoryURL:     "https://github.com/cloudflare/cloudflare-docs/commits/production/src/content/docs/dns/manage-dns-records/reference/record-attributes.mdx",
		PageURL:        "https://developers.cloudflare.com/dns/manage-dns-records/reference/record-attributes/index.md",
		WatchedHeading: "# Record attributes",
		LineFilters: []string{
			"^### Record comments$",
			"^\\| Availability \\| Yes \\| Yes \\| Yes \\| Yes \\|$",
			"^\\| Character limit \\| 100 \\| 500 \\| 500 \\| 500 \\|$",
			"^\\| Comments per record \\| 1 \\| 1 \\| 1 \\| 1 \\|$",
			"^### Record tags$",
			"^\\| Availability \\| No \\| Yes \\| Yes \\| Yes \\|$",
			"^\\| Name character limit \\(everything before the colon\\) \\| N/A \\| 32 \\| 32 \\| 32 \\|$",
			"^\\| Value character limit \\(everything after the colon\\) \\| N/A \\| 100 \\| 100 \\| 100 \\|$",
			"^\\| Tags per record \\| N/A \\| 20 \\| 20 \\| 20 \\|$",
			"^Comments are treated as",
			"^Tags are treated as an array of `name:value` pairs",
		},
		ExpectedLines: []string{
			"### Record comments",
			"| Availability | Yes | Yes | Yes | Yes |",
			"| Character limit | 100 | 500 | 500 | 500 |",
			"| Comments per record | 1 | 1 | 1 | 1 |",
			"### Record tags",
			"| Availability | No | Yes | Yes | Yes |",
			"| Name character limit (everything before the colon) | N/A | 32 | 32 | 32 |",
			"| Value character limit (everything after the colon) | N/A | 100 | 100 | 100 |",
			"| Tags per record | N/A | 20 | 20 | 20 |",
			"Comments are treated as [graphic Unicode characters ↗](https://en.wikipedia.org/wiki/Graphic%5Fcharacter), meaning that they are case-sensitive and do not have any character limitations. However, comments do not support newline (`\\n`) or carriage return (`\\r`) characters.",
			"Tags are treated as an array of `name:value` pairs, meaning that tag names are not case-sensitive and can only contain letters, numbers, `-`, and `_`. For tag values, the same character restrictions apply as for comments.",
		},
		WatchLabel: "Watched record-attribute lines",
		Reminders: []string{
			"Re-check DNS comment and tag reconciliation if Cloudflare changes attribute availability or limits.",
			"Re-check whether tag names remain case-insensitive and constrained to name:value form.",
			"Re-check whether comments still reject newline and carriage-return characters.",
		},
		RelatedPaths: []string{
			"internal/api/tags/tags.go",
			"internal/api/cloudflare_records.go",
			"README.markdown",
		},
	},
	{
		Name:           "Cloudflare DNS TTL semantics",
		Repo:           "cloudflare/cloudflare-docs",
		Ref:            "production",
		Path:           "src/content/docs/dns/manage-dns-records/reference/ttl.mdx",
		SnapshotDate:   "2026-03-22",
		HistoryURL:     "https://github.com/cloudflare/cloudflare-docs/commits/production/src/content/docs/dns/manage-dns-records/reference/ttl.mdx",
		PageURL:        "https://developers.cloudflare.com/dns/manage-dns-records/reference/ttl/index.md",
		WatchedHeading: "# Time to Live (TTL)",
		LineFilters: []string{
			"^By default, all \\[proxied records\\]",
			"^For \\*\\*DNS only\\*\\* records, you can choose a TTL between",
			"^A TTL of \\*\\*Auto\\*\\* is set to 300 seconds",
		},
		ExpectedLines: []string{
			"By default, all [proxied records](https://developers.cloudflare.com/dns/proxy-status/) have a TTL of **Auto**, which is set to 300 seconds. This value cannot be edited.",
			"For **DNS only** records, you can choose a TTL between **30 seconds** (Enterprise) or **60 seconds** (non-Enterprise) and **1 day**.",
			"A TTL of **Auto** is set to 300 seconds (five minutes).",
		},
		WatchLabel: "Watched TTL lines",
		Reminders: []string{
			"Re-check ReadTTL and any user guidance if Cloudflare changes the editable TTL range.",
			"Re-check TTLAuto and any operator-facing TTL wording if Cloudflare changes whether 1 still means automatic TTL.",
			"Re-check whether proxied records still force Auto/300.",
			"Re-check whether non-Enterprise records still have a 60-second floor while Enterprise records allow 30 seconds.",
		},
		RelatedPaths: []string{
			"internal/config/env_base.go",
			"internal/api/ttl.go",
			"internal/api/cloudflare_records.go",
			"README.markdown",
		},
	},
	{
		Name:         "Cloudflare OpenAPI DNS record schema",
		Repo:         "cloudflare/api-schemas",
		Ref:          "main",
		Path:         "openapi.json",
		SnapshotDate: "2026-03-22",
		HistoryURL:   "https://github.com/cloudflare/api-schemas/commits/main/openapi.json",
		JSONPointers: []jsonPointerSelector{
			{Label: "dns-records_ttl.anyOf[0].minimum", Pointer: "/components/schemas/dns-records_ttl/anyOf/0/minimum", Expected: 30},
			{Label: "dns-records_ttl.anyOf[0].maximum", Pointer: "/components/schemas/dns-records_ttl/anyOf/0/maximum", Expected: 86400},
			{Label: "dns-records_ttl.anyOf[1].enum", Pointer: "/components/schemas/dns-records_ttl/anyOf/1/enum", Expected: []int{1}},
			{Label: "dns-records_proxied.type", Pointer: "/components/schemas/dns-records_proxied/type", Expected: "boolean"},
			{Label: "dns-records_comment.type", Pointer: "/components/schemas/dns-records_comment/type", Expected: "string"},
			{Label: "dns-records_tags.items.description", Pointer: "/components/schemas/dns-records_tags/items/description", Expected: "Individual tag of the form name:value (the name must consist of only letters, numbers, underscores and hyphens)"},
		},
		WatchLabel: "Watched OpenAPI DNS-record schema values",
		Reminders: []string{
			"Re-check TTL validation and operator guidance if the OpenAPI TTL bounds change.",
			"Re-check DNS tag semantics if the schema changes the documented name:value form or allowed tag-name characters.",
			"Re-check proxied/comment/tag handling in internal/api/cloudflare_records.go if these field types or descriptions change.",
		},
		RelatedPaths: []string{
			"internal/config/env_base.go",
			"internal/api/ttl.go",
			"internal/api/cloudflare_records.go",
			"internal/api/tags/tags.go",
		},
	},
	{
		Name:         "Cloudflare OpenAPI lists schema",
		Repo:         "cloudflare/api-schemas",
		Ref:          "main",
		Path:         "openapi.json",
		SnapshotDate: "2026-03-22",
		HistoryURL:   "https://github.com/cloudflare/api-schemas/commits/main/openapi.json",
		JSONPointers: []jsonPointerSelector{
			{Label: "lists_name.pattern", Pointer: "/components/schemas/lists_name/pattern", Expected: "^[a-zA-Z0-9_]+$"},
			{Label: "lists_name.maxLength", Pointer: "/components/schemas/lists_name/maxLength", Expected: 50},
			{Label: "lists_kind.enum", Pointer: "/components/schemas/lists_kind/enum", Expected: []string{"ip", "redirect", "hostname", "asn"}},
			{Label: "lists_num_referencing_filters.readOnly", Pointer: "/components/schemas/lists_num_referencing_filters/readOnly", Expected: true},
		},
		WatchLabel: "Watched OpenAPI list-schema values",
		Reminders: []string{
			"Re-check the name-rule conflict between the Lists page and the OpenAPI/JSON-object schema if the list-name pattern changes.",
			"Re-check assumptions about available list kinds and the read-only num_referencing_filters field.",
			"Re-check WAF list create/read handling in internal/api/cloudflare_waf.go if the schema changes.",
		},
		RelatedPaths: []string{
			"internal/config/env_waf.go",
			"internal/api/cloudflare_waf.go",
			"README.markdown",
		},
	},
	{
		Name:         "Cloudflare OpenAPI zones schema",
		Repo:         "cloudflare/api-schemas",
		Ref:          "main",
		Path:         "openapi.json",
		SnapshotDate: "2026-03-22",
		HistoryURL:   "https://github.com/cloudflare/api-schemas/commits/main/openapi.json",
		JSONPointers: []jsonPointerSelector{
			{Label: "zones_zone.status.enum", Pointer: "/components/schemas/zones_zone/properties/status/enum", Expected: []string{"initializing", "pending", "active", "moved"}},
			{Label: "GET /zones status filter enum", Pointer: "/paths/~1zones/get/parameters/1/schema/enum", Expected: []string{"initializing", "pending", "active", "moved"}},
		},
		WatchLabel: "Watched OpenAPI zone-status values",
		Reminders: []string{
			"Re-check zone-status handling in internal/api/cloudflare_records.go if the OpenAPI status enum changes.",
			"Re-check whether Cloudflare's zone-status docs and API schema still disagree about deleted or purged statuses.",
			"Re-check whether the updater should handle newly documented or newly surfaced status values explicitly.",
		},
		RelatedPaths: []string{
			"internal/api/cloudflare_records.go",
			"internal/api/cloudflare_records_zone_test.go",
		},
	},
	{
		Name:           "Cloudflare WAF list availability",
		Repo:           "cloudflare/cloudflare-docs",
		Ref:            "production",
		Path:           "src/content/docs/waf/tools/lists/index.mdx",
		SnapshotDate:   "2026-03-22",
		HistoryURL:     "https://github.com/cloudflare/cloudflare-docs/commits/production/src/content/docs/waf/tools/lists/index.mdx",
		PageURL:        "https://developers.cloudflare.com/waf/tools/lists/index.md",
		WatchedHeading: "## Availability",
		LineFilters: []string{
			"^\\| Number of custom lists \\(any type\\) \\|",
			"^\\| Max\\. number of list items \\(across all custom lists\\) \\|",
			"^\\| IP lists \\|",
			"^\\* The number of available custom lists depends on the highest plan in your account\\.",
		},
		ExpectedLines: []string{
			"| Number of custom lists (any type) | 1 | 10 | 10 | 1,000 |",
			"| Max. number of list items (across all custom lists) | 10,000 | 10,000 | 10,000 | 500,000 |",
			"| IP lists | Yes | Yes | Yes | Yes |",
			"* The number of available custom lists depends on the highest plan in your account. Any account with at least one paid plan will get the highest quota.",
		},
		WatchLabel: "Watched availability lines",
		Reminders: []string{
			"Re-check whether the WAF list config comment about managing only a small number of lists is still justified.",
			"Re-check any user guidance that assumes Free accounts only get one custom list.",
			"Re-check whether IP lists remain available on all plans and whether account-level item caps changed.",
		},
		RelatedPaths: []string{
			"internal/config/env_waf.go",
			"README.markdown",
		},
	},
	{
		Name:           "Cloudflare WAF list deletion rule",
		Repo:           "cloudflare/cloudflare-docs",
		Ref:            "production",
		Path:           "src/content/docs/waf/tools/lists/index.mdx",
		SnapshotDate:   "2026-03-24",
		HistoryURL:     "https://github.com/cloudflare/cloudflare-docs/commits/production/src/content/docs/waf/tools/lists/index.mdx",
		PageURL:        "https://developers.cloudflare.com/waf/tools/lists/index.md",
		WatchedHeading: "## Final remarks",
		LineFilters: []string{
			"^You can only delete a list",
		},
		ExpectedLines: []string{
			"You can only delete a list when no rules (enabled or disabled) reference it.",
		},
		WatchLabel: "Watched list-deletion rule",
		Reminders: []string{
			"Re-check any cleanup or operator guidance that assumes referenced WAF lists cannot be deleted.",
			"Re-check whether Cloudflare still treats disabled rules as blocking list deletion too.",
		},
		RelatedPaths: []string{
			"internal/api/cloudflare_waf.go",
			"README.markdown",
		},
	},
	{
		Name:           "Cloudflare WAF list IP ranges",
		Repo:           "cloudflare/cloudflare-docs",
		Ref:            "production",
		Path:           "src/content/docs/waf/tools/lists/lists-api/json-object.mdx",
		SnapshotDate:   "2026-03-22",
		HistoryURL:     "https://github.com/cloudflare/cloudflare-docs/commits/production/src/content/docs/waf/tools/lists/lists-api/json-object.mdx",
		WatchedSection: "Any of these formats can exist in the same custom list with IP addresses",
		ExpectedBullets: []string{
			"IPv4 address",
			"IPv6 address",
			"IPv4 ranges as /8 through /32 CIDRs",
			"IPv6 ranges as /12 through /128 CIDRs",
		},
		Reminders: []string{
			"Re-check whether Cloudflare still documents mixed exact IP addresses and CIDR ranges in the same IP list.",
			"Re-check the documented IPv4 CIDR bounds, currently /8 through /32.",
			"Re-check the documented IPv6 CIDR bounds, currently /12 through /128.",
			"Re-check whether exact IPv6 addresses remain supported, because that affects the live /64 versus /128 default discussion.",
		},
		RelatedPaths: []string{
			"docs/designs/features/ipv6-default-prefix-length-policy.markdown",
			"docs/designs/features/lifecycle-model.markdown",
			"internal/api/cloudflare_waf_list_items_test.go",
			"internal/setter/setter.go",
			"internal/updater/updater.go",
		},
	},
	{
		Name:           "Cloudflare WAF list JSON-object name rules",
		Repo:           "cloudflare/cloudflare-docs",
		Ref:            "production",
		Path:           "src/content/docs/waf/tools/lists/lists-api/json-object.mdx",
		SnapshotDate:   "2026-03-27",
		HistoryURL:     "https://github.com/cloudflare/cloudflare-docs/commits/production/src/content/docs/waf/tools/lists/lists-api/json-object.mdx",
		PageURL:        "https://developers.cloudflare.com/waf/tools/lists/lists-api/json-object/index.md",
		WatchedHeading: "## List object structure and properties",
		LineFilters: []string{
			"^\\| name String ",
		},
		ExpectedLines: []string{
			"| name String | An informative name for the list. | Maximum length: 50 characters.Only alphanumeric and underscore (\\_) characters are valid.A valid name satisfies this regular expression: ^\\[a-zA-Z0-9\\_\\]+$. |",
		},
		WatchLabel: "Watched JSON-object name-rule line",
		Reminders: []string{
			"Re-check the documented conflict between the Lists page lowercase-only rule and the JSON-object page alphanumeric rule.",
			"Re-check whether warnings in internal/config/env_waf.go should stay lowercase-only.",
			"Re-check whether uppercase list names should be accepted, warned on, or normalized.",
		},
		RelatedPaths: []string{
			"internal/config/env_waf.go",
			"internal/config/env_waf_test.go",
			"README.markdown",
		},
	},
	{
		Name:           "Cloudflare WAF list name rules",
		Repo:           "cloudflare/cloudflare-docs",
		Ref:            "production",
		Path:           "src/content/docs/waf/tools/lists/index.mdx",
		SnapshotDate:   "2026-03-22",
		HistoryURL:     "https://github.com/cloudflare/cloudflare-docs/commits/production/src/content/docs/waf/tools/lists/index.mdx",
		PageURL:        "https://developers.cloudflare.com/waf/tools/lists/index.md",
		WatchedHeading: "## List names",
		LineFilters: []string{
			"^\\* ",
		},
		ExpectedLines: []string{
			"* The name uses only lowercase letters, numbers, and the underscore (`_`) character in the name. A valid name satisfies this regular expression: `^[a-z0-9_]+$`.",
			"* The maximum length of a list name is 50 characters.",
		},
		WatchLabel: "Watched list-name rules",
		Reminders: []string{
			"Re-check whether warnings on characters outside ^[a-z0-9_]+$ still match Cloudflare's user-facing docs.",
			"Re-check whether list names remain lowercase-only or whether uppercase should be accepted or normalized.",
			"Re-check the documented maximum list-name length.",
		},
		RelatedPaths: []string{
			"internal/config/env_waf.go",
			"internal/config/env_waf_test.go",
			"README.markdown",
		},
	},
	{
		Name:           "Cloudflare zone status docs",
		Repo:           "cloudflare/cloudflare-docs",
		Ref:            "production",
		Path:           "src/content/docs/dns/zone-setups/reference/domain-status.mdx",
		SnapshotDate:   "2026-03-22",
		HistoryURL:     "https://github.com/cloudflare/cloudflare-docs/commits/production/src/content/docs/dns/zone-setups/reference/domain-status.mdx",
		PageURL:        "https://developers.cloudflare.com/dns/zone-setups/reference/domain-status/index.md",
		WatchedHeading: "# Zone status",
		LineFilters: []string{
			"^## ",
		},
		ExpectedLines: []string{
			"## Initializing (Finish setup)",
			"## Pending",
			"## Active",
			"## Moved",
			"## Deleted",
			"## Purged",
		},
		WatchLabel: "Watched zone-status headings",
		Reminders: []string{
			"Re-check zone-status handling in internal/api/cloudflare_records.go if Cloudflare adds or removes documented zone states.",
			"Re-check whether the API schema and docs still disagree about deleted or purged states.",
			"Re-check whether warnings or skips for non-active zones should change.",
		},
		RelatedPaths: []string{
			"internal/api/cloudflare_records.go",
			"internal/api/cloudflare_records_zone_test.go",
		},
	},
	{
		Name:           "Cloudflare zone status flow diagram",
		Repo:           "cloudflare/cloudflare-docs",
		Ref:            "production",
		Path:           "src/content/docs/dns/zone-setups/reference/domain-status.mdx",
		SnapshotDate:   "2026-04-19",
		HistoryURL:     "https://github.com/cloudflare/cloudflare-docs/commits/production/src/content/docs/dns/zone-setups/reference/domain-status.mdx",
		PageURL:        "https://developers.cloudflare.com/dns/zone-setups/reference/domain-status/index.md",
		WatchedHeading: "# Zone status",
		LineFilters: []string{
			`^[A-Za-z][A-Za-z0-9_]*\[[^\]]+\]$`,
		},
		ExpectedLines: []string{
			"A[Initializing]",
			"B[Pending]",
			"C[Active]",
			"D[Moved]",
			"E[Deleted]",
			"F[Purged]",
		},
		WatchLabel: "Watched zone-status flow-diagram nodes",
		Reminders: []string{
			"Re-check zone-status handling in internal/api/cloudflare_records.go if Cloudflare adds or removes nodes in the zone-status flow.",
			"Re-check whether any newly introduced status needs explicit active / non-active handling in the updater.",
		},
		RelatedPaths: []string{
			"internal/api/cloudflare_records.go",
			"internal/api/cloudflare_records_zone_test.go",
		},
	},
}
