name: Links

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  local-links:
    name: In-repo
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 🛡️ Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
          disable-sudo: true
          policy: go-tooling

      - name: 🚚 Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: 🏗️ Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26.1"
          cache-dependency-path: scripts/github-actions/link-check/go.mod
      - name: 📡 Run `go telemetry on`
        run: |
          go telemetry on
      - name: 🔎 Check repository-local links
        working-directory: scripts/github-actions/link-check
        run: go run . local
